site_name: CLW Documentation
theme: mkdocs

pages:
- ['index.md', 'Home']
- ['installguide/adminserver/clwrepo.md', 'Admin Server', 'CLW-repo']
- ['installguide/adminserver/clwrepo2.md', 'Admin Server', 'CLW-repo2']
- ['installguide/adminserver/elasticsearch.md', 'Admin Server', 'ElasticSearch']
- ['installguide/adminserver/graphite.md', 'Admin Server', 'Graphite']
- ['installguide/adminserver/jenkins.md', 'Admin Server', 'Jenkins']
- ['installguide/adminserver/ocs.md', 'Admin Server', 'OCS Inventory']
- ['installguide/adminserver/zabbix.md', 'Admin Server', 'Zabbix']
- ['network/openwrt.md', 'Network', 'openwrt']
- ['network/vyos.md', 'Network', 'vyos']
- ['tools/ansible.md', 'Tools', 'ansible']
- ['tools/git.md', 'Tools', 'git']
- ['tools/vim.md', 'Tools', 'vim']
- ['virtualization/docker/docker.md', 'Virtualization', 'Docker']
- ['virtualization/opennebula.md', 'Virtualization', 'OpenNebula']
- ['virtualization/virsh.md', 'Virtualization', 'Virsh']

